import type { Metadata } from 'next';
import { libraryStatistics } from '@/lib/library-statistics';

export const metadata: Metadata = {
  title: 'About | RUNBACK',
  description: 'About RUNBACK, a multi-game roguelike field guide library.',
};

export default function AboutPage() {
  return <main className="min-h-screen bg-[#111417] px-5 py-10 text-[#f1f3f4] sm:px-10 lg:px-16"><div className="mx-auto max-w-3xl"><a href="/" className="font-mono text-xs font-bold tracking-[0.2em] text-[#ff8662]">← RUNBACK</a><p className="mt-12 text-xs font-bold uppercase tracking-[0.2em] text-[#74818a]">About RUNBACK</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em]">Field guides for games where the run can fall apart.</h1><p className="mt-5 text-base leading-relaxed text-[#aeb7bc]">RUNBACK is built to hold practical guides for multiple roguelike and extraction-roguelite games. Games have their own guide libraries with guides, Wiki sections and reference pages. The R.E.P.O. library also includes a visual enemy index.</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-white/[0.08] bg-white/[0.03] p-5"><div className="font-mono text-2xl font-bold text-white">{String(libraryStatistics.gameCount).padStart(2, '0')}</div><p className="mt-2 text-sm text-[#9da8ae]">Game Libraries</p></div><div className="rounded-xl border border-white/[0.08] bg-white/[0.03] p-5"><div className="font-mono text-2xl font-bold text-white">{libraryStatistics.publicContentPageCount}</div><p className="mt-2 text-sm text-[#9da8ae]">Guide &amp; Reference Pages</p></div></div><div className="mt-10 space-y-8 text-sm leading-7 text-[#c7ced3]"><section><h2 className="text-lg font-semibold text-white">What belongs here</h2><p className="mt-2">Short answers for a first run, detailed route and enemy reads, upgrade decisions, co-op roles, patch updates, and mechanics explainers that help players make a safer decision in the next room.</p></section><section><h2 className="text-lg font-semibold text-white">How the library grows</h2><p className="mt-2">Each game is organized as its own library with categories for its content. Guides focus on practical steps and decisions, while Wiki and reference pages organize game mechanics, items and encounters.</p></section></div><div className="mt-12 border-t border-white/[0.08] pt-6 text-xs text-[#74818a]"><a href="/editorial" className="text-[#ff8662] hover:text-white">Editorial policy</a><span className="px-2">·</span><a href="/privacy" className="text-[#ff8662] hover:text-white">Privacy</a></div></div></main>;
}
