import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Editorial Policy | RUNBACK',
  description: 'How RUNBACK researches, rewrites, credits, and updates roguelike guides.',
};

export default function EditorialPage() {
  return <main className="min-h-screen bg-[#111417] px-5 py-10 text-[#f1f3f4] sm:px-10 lg:px-16"><div className="mx-auto max-w-3xl"><a href="/" className="font-mono text-xs font-bold tracking-[0.2em] text-[#ff8662]">← RUNBACK</a><p className="mt-12 text-xs font-bold uppercase tracking-[0.2em] text-[#74818a]">Editorial policy</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em]">Useful, version-aware, and clear about uncertainty.</h1><p className="mt-5 text-base leading-relaxed text-[#aeb7bc]">RUNBACK turns research, patch notes, and original testing into practical field guides for roguelike and extraction-roguelite players.</p><div className="mt-10 space-y-8 text-sm leading-7 text-[#c7ced3]"><section><h2 className="text-lg font-semibold text-white">Sources</h2><p className="mt-2">Official patch notes are the factual anchor for changes. Community guides, videos, forums, and wikis help us discover questions, terminology, and test ideas. We rewrite in original language and link the source trail; we do not present copied prose, subtitles, or screenshots as our own.</p></section><section><h2 className="text-lg font-semibold text-white">Version discipline</h2><p className="mt-2">Prices, damage, spawn tiers, timings, physics, and UI behavior can change during Early Access. When sources disagree, the page says so and favors a reproducible behavior rule over a hard-coded number. Readers should treat the current client as the final authority.</p></section><section><h2 className="text-lg font-semibold text-white">Images</h2><p className="mt-2">Enemy reference images are credited to the source page and used as research/identification references. Image ownership remains with the respective rights holders. We avoid implying endorsement and will replace or remove an image when a rights holder requests it.</p></section><section><h2 className="text-lg font-semibold text-white">Corrections</h2><p className="mt-2">If a guide is wrong or stale, the correction should identify the game version, the disputed claim, and the evidence that changes it. Future releases will add a direct correction channel if reader submissions are enabled.</p></section></div><div className="mt-12 border-t border-white/[0.08] pt-6 text-xs text-[#74818a]">Independent project · <a href="/privacy" className="text-[#ff8662] hover:text-white">Privacy notes</a></div></div></main>;
}
