import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy | RUNBACK',
  description: 'Privacy notes for the RUNBACK roguelike field guide library.',
};

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#111417] px-5 py-10 text-[#f1f3f4] sm:px-10 lg:px-16"><div className="mx-auto max-w-3xl"><a href="/" className="font-mono text-xs font-bold tracking-[0.2em] text-[#ff8662]">← RUNBACK</a><p className="mt-12 text-xs font-bold uppercase tracking-[0.2em] text-[#74818a]">Privacy</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em]">A small site with a small data footprint.</h1><p className="mt-5 text-base leading-relaxed text-[#aeb7bc]">RUNBACK is an independent guide library. This page explains what the current site does and does not collect.</p><div className="mt-10 space-y-8 text-sm leading-7 text-[#c7ced3]"><section><h2 className="text-lg font-semibold text-white">What we collect</h2><p className="mt-2">The current site does not require an account, does not ask for a name or email, and does not run advertising or analytics tracking. The “Save guide” control is a temporary in-browser preference and is not sent to a server.</p></section><section><h2 className="text-lg font-semibold text-white">External links and images</h2><p className="mt-2">Guide pages link to official patch notes and third-party research. Those sites may have their own cookies, logs, analytics, or privacy policies. Enemy reference images are loaded from their credited source host; visiting or loading an external asset may expose a technical request to that host.</p></section><section><h2 className="text-lg font-semibold text-white">Hosting</h2><p className="mt-2">The hosting provider may process technical request information needed to deliver the site, prevent abuse, and maintain availability. RUNBACK does not intentionally combine that information with a user profile.</p></section><section><h2 className="text-lg font-semibold text-white">Changes</h2><p className="mt-2">If the site later adds accounts, comments, newsletters, analytics, or saved cloud data, this page will be updated before that feature is introduced.</p></section></div><div className="mt-12 border-t border-white/[0.08] pt-6 text-xs text-[#74818a]">Last reviewed: September 2026 · <a href="/editorial" className="text-[#ff8662] hover:text-white">Read the editorial policy</a></div></div></main>;
}
