'use client';

import { useState } from 'react';
import { ArrowUpRight, BookOpen, ChevronRight, Crosshair, Flame, Grid2X2, Menu, Search, Settings2, Shield, Sparkles, Swords, Trophy, Users, X, Zap } from 'lucide-react';

const navItems = [
  { label: 'Dashboard', icon: Grid2X2 },
  { label: 'Build Lab', icon: Swords },
  { label: 'Tier List', icon: Trophy },
  { label: 'Routes & Maps', icon: Crosshair },
  { label: 'Enemy Intel', icon: Shield },
];
const guides = [
  { tag: 'BUILD', title: 'The “never stop moving” loadout', meta: '12 min read · Updated today', color: 'orange' },
  { tag: 'ROUTE', title: 'Best loot path for a clean extraction', meta: '8 min read · Patch 0.4', color: 'blue' },
  { tag: 'BASICS', title: '5 mistakes every new crew makes', meta: '6 min read · For beginners', color: 'green' },
];
const tierRows = [
  { tier: 'S', items: ['Gun', 'Shotgun', 'Dynamite'], accent: 'bg-[#ff7043]', note: 'Always worth the slot' },
  { tier: 'A', items: ['Stun Grenade', 'Strength', 'Tracker'], accent: 'bg-[#f6c453]', note: 'Strong with a plan' },
  { tier: 'B', items: ['Bow', 'Health Pack', 'Human Grenade'], accent: 'bg-[#7d8f9f]', note: 'Run-dependent' },
];

function BrandMark() {
  return <div className="flex items-center gap-3"><div className="relative flex h-9 w-9 items-center justify-center rounded-[10px] bg-[#ff7043] text-[#111417] shadow-[0_0_24px_rgba(255,112,67,0.28)]"><span className="absolute left-[8px] top-[7px] h-[11px] w-[11px] rounded-[3px] border-[2px] border-[#111417]" /><span className="absolute bottom-[7px] right-[7px] h-[10px] w-[10px] rotate-45 border-[2px] border-[#111417]" /></div><div><div className="font-mono text-[15px] font-bold tracking-[0.22em] text-white">RUNBACK</div><div className="mt-0.5 text-[8px] font-semibold uppercase tracking-[0.24em] text-[#84909b]">The R.E.P.O. field guide</div></div></div>;
}

export default function Home() {
  const [activeNav, setActiveNav] = useState('Dashboard');
  const [mobileNav, setMobileNav] = useState(false);
  const [query, setQuery] = useState('');
  const [saved, setSaved] = useState(false);

  return <main className="min-h-screen bg-[#111417] text-[#f1f3f4] selection:bg-[#ff7043] selection:text-[#111417]">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_70%_0%,rgba(255,112,67,0.09),transparent_28%),radial-gradient(circle_at_0%_90%,rgba(74,125,153,0.08),transparent_30%)]" />
    <div className="relative mx-auto flex min-h-screen max-w-[1600px]">
      <aside className={`fixed inset-y-0 left-0 z-30 w-[246px] border-r border-white/[0.07] bg-[#111417] px-7 py-7 transition-transform lg:sticky lg:top-0 lg:flex lg:h-screen lg:translate-x-0 lg:flex-col ${mobileNav ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="mb-12 flex items-center justify-between lg:block"><BrandMark /><button aria-label="Close navigation" onClick={() => setMobileNav(false)} className="rounded-lg p-2 text-[#84909b] hover:bg-white/5 hover:text-white lg:hidden"><X size={20} /></button></div>
        <div className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#64717c]">Explore</div>
        <nav className="space-y-1">{navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActiveNav(label); setMobileNav(false); }} className={`group flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] transition ${activeNav === label ? 'bg-white/[0.08] text-white' : 'text-[#8a959e] hover:bg-white/[0.04] hover:text-white'}`}><Icon size={17} strokeWidth={activeNav === label ? 2.4 : 1.8} className={activeNav === label ? 'text-[#ff7043]' : 'text-[#64717c] group-hover:text-[#aeb8c0]'} /><span>{label}</span>{label === 'Build Lab' && <span className="ml-auto rounded bg-[#ff7043]/15 px-1.5 py-0.5 font-mono text-[9px] text-[#ff9a78]">BETA</span>}</button>)}</nav>
        <div className="my-9 h-px bg-white/[0.07]" /><div className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#64717c]">Your crew</div>
        <div className="space-y-1"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-[13px] text-[#8a959e] transition hover:bg-white/[0.04] hover:text-white"><Users size={17} className="text-[#64717c]" /> Find a crew <span className="ml-auto text-[#64717c]">↗</span></button><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-[13px] text-[#8a959e] transition hover:bg-white/[0.04] hover:text-white"><BookOpen size={17} className="text-[#64717c]" /> Saved guides <span className="ml-auto font-mono text-[10px] text-[#64717c]">04</span></button></div>
        <div className="mt-auto rounded-2xl border border-white/[0.07] bg-white/[0.035] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#64717c]">Live patch</span><span className="flex items-center gap-1.5 text-[10px] font-semibold text-[#79c7a0]"><span className="h-1.5 w-1.5 rounded-full bg-[#79c7a0]" /> ONLINE</span></div><div className="font-mono text-[13px] font-bold text-white">v0.4.0 · THE LOOP</div><p className="mt-1 text-[11px] leading-relaxed text-[#7c8790]">The latest intel is synced for your next run.</p><button className="mt-4 flex items-center gap-1 text-[11px] font-semibold text-[#ff8662] hover:text-[#ffb099]">View patch notes <ArrowUpRight size={13} /></button></div>
      </aside>

      <section className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-white/[0.07] bg-[#111417]/90 px-5 backdrop-blur-xl sm:px-9"><button aria-label="Open navigation" onClick={() => setMobileNav(true)} className="rounded-lg p-2 text-[#84909b] hover:bg-white/5 hover:text-white lg:hidden"><Menu size={21} /></button><div className="relative hidden w-full max-w-[410px] sm:block"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#64717c]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search guides, items, enemies..." className="h-10 w-full rounded-xl border border-white/[0.08] bg-white/[0.04] pl-10 pr-4 text-[12px] text-white outline-none placeholder:text-[#66727c] focus:border-[#ff7043]/60" /></div><div className="ml-auto flex items-center gap-4"><button className="hidden items-center gap-2 text-[12px] font-medium text-[#89949c] transition hover:text-white md:flex"><Settings2 size={16} /> Preferences</button><div className="h-7 w-px bg-white/[0.08]" /><button className="flex items-center gap-2 rounded-full border border-white/[0.09] bg-white/[0.04] py-1.5 pl-1.5 pr-3 text-[11px] font-semibold text-[#c7ced3] hover:border-white/20"><div className="flex h-6 w-6 items-center justify-center rounded-full bg-[#30475a] text-[9px] text-[#d8e6ee]">JS</div> JesterSocks</button></div></header>

        <div className="mx-auto max-w-[1250px] px-5 pb-16 pt-8 sm:px-9 lg:px-12 lg:pt-11"><div className="mb-10 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="mb-4 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-[#ff8060]"><Sparkles size={13} /> Field guide / dashboard</div><h1 className="max-w-[720px] text-4xl font-semibold tracking-[-0.04em] text-white sm:text-[52px] sm:leading-[1.02]">Make the next run<br /><span className="text-[#ff7043]">count.</span></h1><p className="mt-5 max-w-[560px] text-[14px] leading-relaxed text-[#8d989f]">Curated intel for crews who would rather extract with the good loot. Builds, routes, and enemy reads for R.E.P.O. players.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#79c7a0]/20 bg-[#79c7a0]/[0.06] px-3 py-2 text-[11px] font-medium text-[#9fd7ba]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#79c7a0]" /> 1,284 crews online <span className="text-[#5f8f78]">·</span> patch v0.4.0</div></div>

          <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.75fr)]"><article className="group relative min-h-[340px] overflow-hidden rounded-2xl border border-white/[0.09] bg-[#192126] p-7 sm:p-9"><img src="https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1400&q=80" alt="A moody gaming setup" className="absolute inset-0 h-full w-full object-cover opacity-[0.17] mix-blend-screen transition duration-700 group-hover:scale-105 group-hover:opacity-[0.22]" /><div className="absolute inset-0 bg-gradient-to-r from-[#192126] via-[#192126]/90 to-[#192126]/35" /><div className="relative flex h-full flex-col justify-between"><div><div className="mb-8 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#ff8662]"><Flame size={14} fill="currentColor" /> Trending this week</div><h2 className="max-w-[510px] text-3xl font-semibold leading-[1.08] tracking-[-0.03em] text-white sm:text-[40px]">The 0.4 meta is<br />all about <span className="text-[#ff7043]">tempo.</span></h2><p className="mt-4 max-w-[430px] text-[13px] leading-relaxed text-[#abb4ba]">Fast clears, flexible carry weight, and knowing when to leave. Here&apos;s what top crews are running right now.</p></div><div className="mt-8 flex flex-wrap items-center gap-3"><button className="flex items-center gap-2 rounded-lg bg-[#ff7043] px-4 py-2.5 text-[12px] font-bold text-[#16191b] transition hover:bg-[#ff8965]">Read the breakdown <ArrowUpRight size={15} /></button><span className="text-[11px] text-[#89949c]">Updated 2h ago · 9 min read</span></div></div></article>

            <article className="rounded-2xl border border-white/[0.09] bg-[#161b1f] p-6 sm:p-7"><div className="mb-6 flex items-start justify-between"><div><div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#74818a]">Quick reference</div><h2 className="text-xl font-semibold tracking-[-0.02em] text-white">Community tier list</h2></div><button className="rounded-lg p-2 text-[#66737d] transition hover:bg-white/5 hover:text-white"><ArrowUpRight size={17} /></button></div><div className="space-y-3">{tierRows.map((row) => <div key={row.tier} className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${row.accent} font-mono text-[13px] font-bold text-[#15191b]`}>{row.tier}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5">{row.items.map((item) => <span key={item} className="rounded-md border border-white/[0.08] bg-white/[0.04] px-2 py-1 text-[10px] font-medium text-[#cbd2d6]">{item}</span>)}</div><div className="mt-1 text-[10px] text-[#66737d]">{row.note}</div></div></div>)}</div><div className="mt-6 border-t border-white/[0.07] pt-4 text-[11px] text-[#79858e]">Based on <span className="font-semibold text-[#b8c0c5]">2,491</span> community votes <span className="mx-1 text-[#4c5962]">·</span> <button className="font-semibold text-[#ff8662] hover:text-[#ffb099]">See full list</button></div></article></div>

          <div className="mt-9 grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.75fr)]"><section><div className="mb-5 flex items-end justify-between"><div><div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#74818a]">Worth your time</div><h2 className="text-2xl font-semibold tracking-[-0.03em] text-white">Latest field notes</h2></div><button className="flex items-center gap-1 text-[11px] font-semibold text-[#ff8662] hover:text-[#ffb099]">Browse all <ChevronRight size={14} /></button></div><div className="space-y-3">{guides.map((guide, index) => <button key={guide.title} className="group flex w-full items-center gap-4 rounded-xl border border-white/[0.07] bg-[#161b1f] p-4 text-left transition hover:-translate-y-0.5 hover:border-white/[0.16] hover:bg-[#1a2126]"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-xl ${guide.color === 'orange' ? 'bg-[#ff7043]/15 text-[#ff8662]' : guide.color === 'blue' ? 'bg-[#4a7d99]/20 text-[#77abc6]' : 'bg-[#79c7a0]/15 text-[#8ed6b1]'}`}><span className="font-mono text-[16px] font-bold">0{index + 1}</span></div><div className="min-w-0 flex-1"><div className="mb-1 text-[9px] font-bold tracking-[0.18em] text-[#ff8662]">{guide.tag}</div><h3 className="truncate text-[14px] font-semibold text-[#e5e9eb] group-hover:text-white">{guide.title}</h3><p className="mt-1 text-[11px] text-[#6f7b84]">{guide.meta}</p></div><ArrowUpRight size={17} className="shrink-0 text-[#52606a] transition group-hover:text-[#ff8662]" /></button>)}</div></section>

            <aside className="rounded-2xl border border-white/[0.09] bg-[#161b1f] p-6 sm:p-7"><div className="mb-7 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#ff7043]/15 text-[#ff8662]"><Zap size={17} fill="currentColor" /></div><div><div className="text-[10px] font-semibold uppercase tracking-[0.17em] text-[#74818a]">Run of the day</div><h2 className="text-base font-semibold text-white">The Glass Cannon</h2></div></div><div className="space-y-5"><div><div className="mb-2 flex justify-between text-[11px]"><span className="text-[#aab3b8]">Difficulty</span><span className="font-mono font-bold text-[#ff8662]">HIGH RISK</span></div><div className="flex gap-1"><span className="h-1.5 flex-1 rounded-full bg-[#ff7043]" /><span className="h-1.5 flex-1 rounded-full bg-[#ff7043]" /><span className="h-1.5 flex-1 rounded-full bg-[#ff7043]" /><span className="h-1.5 flex-1 rounded-full bg-[#ff7043]" /><span className="h-1.5 flex-1 rounded-full bg-[#343d43]" /></div></div><div className="flex items-center justify-between border-t border-white/[0.07] pt-4 text-[11px]"><span className="text-[#79858e]">Core loop</span><span className="font-semibold text-[#d6dcdf]">Speed + damage</span></div><div className="flex items-center justify-between text-[11px]"><span className="text-[#79858e]">Best with</span><span className="font-semibold text-[#d6dcdf]">2–3 players</span></div></div><button onClick={() => setSaved(!saved)} className={`mt-7 flex w-full items-center justify-center gap-2 rounded-lg border py-2.5 text-[11px] font-bold transition ${saved ? 'border-[#79c7a0]/40 bg-[#79c7a0]/10 text-[#9fd7ba]' : 'border-white/[0.1] text-[#abb5ba] hover:border-[#ff7043]/50 hover:text-white'}`}><BookOpen size={14} /> {saved ? 'Saved to your guides' : 'Save this run'}</button></aside></div>

          <footer className="mt-14 flex flex-col gap-3 border-t border-white/[0.07] pt-5 text-[10px] text-[#59656d] sm:flex-row sm:items-center sm:justify-between"><div>RUNBACK is a fan-made field guide for R.E.P.O. players.</div><div className="flex gap-4"><span>Data last synced 4m ago</span><span className="text-[#71808a]">Discord ↗</span></div></footer>
        </div>
      </section>
    </div>
  </main>;
}
