'use client';

import { useMemo, useState } from 'react';
import { ArrowUpRight, BookOpen, ChevronRight, Crosshair, Flame, Grid2X2, Menu, Search, Shield, Swords, Trophy, Users, X, Zap } from 'lucide-react';

type Guide = {
  id: string;
  tag: string;
  title: string;
  summary: string;
  lead: string;
  steps: string[];
  mistakes: string;
  risk: string;
  sources: { label: string; href: string }[];
};

const guides: Guide[] = [
  { id: 'P0-1', tag: '首局流程', title: '第一次也能安全跑完一趟', summary: '从 Tutorial、出车、搬运到回到 Service Station 的完整首局路线。', lead: '首局目标是安全完成一趟：做 Tutorial，进单人或 1–6 人房间；出车推 C.A.R.T.，先搬近处易控物品。物品入 extraction point、达到 quota 后回 truck，再按失败原因买升级。', steps: ['先在 Tutorial 或 Settings → Controls 熟悉移动、抓取、调整物品、地图和冲刺。', '出车后先找到并推动 C.A.R.T.，优先拿近处、完整、容易过门的 valuables。', '把物品带到 extraction point，确认完整入区并达到 quota；不要为了最后一件货绕远路。', '完成提取后沿地图提示回 truck，队伍集合后再离场。', '回到 Service Station，只买一个最能解决上一局失败原因的升级。'], mistakes: '大件卡门、全队离车太远、搬运时没有报怪，以及把“达到目标”误解成“必须清空地图”。', risk: '本地客户端以 v0.4.0 为基准；公网资料包含后续版本，按键和 UI 以当前设置为准。', sources: [{ label: '官方 v0.4.0', href: 'https://store.steampowered.com/news/app/3241660/view/653728111564685329?l=schinese' }, { label: '入门流程', href: 'https://www.repo-game.org/en/repogame-how-to-play' }] },
  { id: 'P0-2', tag: '配额', title: '先交付，再贪多', summary: '把 quota 当成撤离门槛，而不是清空地图的任务。', lead: '看 HUD 和点位数量，优先搬近处、完整、易控的 valuables，用 C.A.R.T. 做中转，完整放进提取区。达到目标就撤，给回程和失误留余量。', steps: ['出车后先确认目标值、提取点数量和回 truck 的方向。', '先拿近处高价值但不容易损坏的物品；大件留到路线稳定后再处理。', '用 C.A.R.T. 做中转，减少队友在危险区反复往返。', '物品完全进入边界后再离开，观察点位是否完成。', '达到 quota 后停止贪多，优先把队伍和已交付收益带回车。'], mistakes: '为了最后一件物品进入未知区域；把擦到边界的物品当成已交付；忽略回程时间。', risk: '配额公式、超额结算和多人缩放可能随版本变化，正文不写死金额公式。', sources: [{ label: '配额说明', href: 'https://www.repo-game.org/zh/repogame-quota' }, { label: '撤离流程', href: 'https://dotesports.com/indies/news/how-to-extract-in-r-e-p-o' }] },
  { id: 'P0-3', tag: '撤离', title: '提取点完成后怎么回车', summary: '物品入区、点位结算、队伍回车，三段式完成撤离。', lead: '撤离只有三件事：物品完整入区、所有 extraction point 完成、队伍回到 truck。不要站平台等结算，也别漏点位。', steps: ['进图初期打开地图或由侦察位记住提取点和 truck 的方向。', '慢慢调整贵重物，让它完全进入边界；大件先清空间再放。', '平台结算时不要站在其中等待，避免被压伤或挡住判定。', '确认所有点位完成后，沿地图提示回 truck，队伍不要分散。', '在车内完成离场确认；不要把“回到车边”误认为已经结算。'], mistakes: '漏点位、边界擦碰、平台站位压伤、回程有人掉队。', risk: '不同攻略对站位、复活和离场确认的描述存在版本差异，最终按钮以当前客户端为准。', sources: [{ label: '撤离攻略', href: 'https://dotesports.com/indies/news/how-to-extract-in-r-e-p-o' }, { label: '官方公告', href: 'https://store.steampowered.com/news/app/3241660/view/653728111564685329?l=schinese' }] },
  { id: 'P0-4', tag: '升级', title: '前期升级按失败原因买', summary: '搬不动、体力断、够不到或总被击倒，对应不同解法。', lead: '升级按失败原因买：搬不动或耗时长，优先 Strength/Stamina；常被击倒，选 Health；够不到物品，选 Range。下一局只改一个变量。', steps: ['先复盘上一局的第一死因，而不是直接照抄 tier list。', '搬运效率低看 Strength，动作经常断档看 Stamina。', '受伤是主要死因再买 Health；贴近危险才能拿货时考虑 Range。', '多人按职责分配：搬运位优先能力，侦察位优先生存和机动。', '买完跑一趟验证，只记录一个升级带来的变化。'], mistakes: '把“社区推荐”当成固定答案；只看价格不看队伍职责；一局买太多种能力导致无法判断收益。', risk: '价格、库存、升级池和最佳顺序会变化，本站优先发布效果和决策逻辑。', sources: [{ label: '升级说明', href: 'https://www.repo-game.org/en/repogame-upgrades' }, { label: '社区升级指南', href: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3482961802&l=english' }] },
  { id: 'P0-5', tag: '升级', title: '升级效果与优先级', summary: '用“它替你解决什么问题”来读升级，比背价格表更耐版本变化。', lead: '升级分四类：Stamina/Health 保生存，Strength/Range 解搬运，Sprint/Tumble/Jump 改机动，Map Player Count 是信息工具。先看效果与职责，再看价格。', steps: ['生存底盘：经常体力断档看 Stamina，频繁受伤看 Health。', '搬运能力：Strength 影响可搬重量和物理处理，Range 提高抓取或互动距离。', '机动能力：Sprint Speed、Tumble Launch、Extra Jump 解决过门、回程和脱险。', '信息与控制：地图类工具提高判断，控制类道具用于绕开危险窗口。', '记录当前版本效果和价格，更新攻略时标注版本号。'], mistakes: '把旧版本数字直接套到新版本；忽略单人不生成部分升级；把工具的存在当成必须购买。', risk: '官方 v0.4.0 公告明确提到单人不生成 Map Player Count 与 Death Head Battery；具体库存仍需当前客户端核对。', sources: [{ label: '官方 v0.4.0', href: 'https://store.steampowered.com/news/app/3241660/view/653728111564685329?l=schinese' }, { label: '物品说明', href: 'https://twinfinite.net/guides/all-items-in-repo-how-use-them/' }] },
  { id: 'P0-6', tag: '力量', title: 'Strength 4/9/13 只能当测试起点', summary: '社区常见断点不等于当前版本官方硬门槛。', lead: '把 4/9/13 当成测试节点：各测一件大件和一个怪物，记录能否抓起、是否减速、能否过门、多人合抓是否改变结果。', steps: ['固定关卡、物品、距离、人数和版本，先记录基础值。', '测试 Strength 4：观察目标是完全不能抓，还是可抓但很慢。', '测试 Strength 9 与 13，重复同一组物品和怪物。', '记录“能否抓起、是否减速、是否卡门、是否能交付”。', '只发布自己复现的断点，并把测试条件写在正文中。'], mistakes: '直接写“13 就能搬全部”；把不同物品和怪物混为同一重量体系；忽略近战和物理手感的版本修复。', risk: '4/9/13 来自社区与第三方图表，适合作为复测设计，不替代当前版本数据。', sources: [{ label: '力量图表', href: 'https://www.destructoid.com/r-e-p-o-strength-chart-how-many-strength-upgrades-do-you-need-to-grab-everything/' }, { label: '官方 v0.4.4', href: 'https://store.steampowered.com/news/posts/?enddate=1779701754&feed=steam_community_announcements' }] },
  { id: 'P0-7', tag: '怪物', title: '先判断触发类型，再决定打不打', summary: '新手第一反应不是冲上去打，而是弄清楚怪物靠什么发现你。', lead: '遇怪先判断视线、声音、距离或特殊触发：视线型找遮挡，声音型降噪，近距离型拉开，特殊型记动作。标准顺序是报点、停搬、留退路、绕行。', steps: ['看到或听到提示，先报怪物位置和方向。', '停止搬运，把物品放在不会挡退路的位置。', '视线型找门、墙、容器遮挡；声音型少冲刺、少跳跃、轻放物品。', '近距离型拉开距离，不在窄门硬挤；特殊型优先记触发动作。', '只有队伍有明确武器、开阔空间和撤退路线时才考虑反制。'], mistakes: '没有报点就继续搬；在窄门硬挤；为了物品把队伍带入未知房间。', risk: '怪物数量、危险等级和伤害属于版本敏感信息，速查只保留可复现字段。', sources: [{ label: '怪物指南', href: 'https://www.switchbladegaming.com/co-op-games/repo/all-monsters-guide-2026/' }, { label: '中文怪物整理', href: 'https://www.taptap.cn/moment/660569358711393580' }] },
  { id: 'P0-8', tag: '怪物', title: 'Shadow Child：听到笑声先别回头看', summary: '把识别、转身、拉开距离和复测分开处理。', lead: 'Shadow Child 出现笑声或黑色细长身影时，不要持续注视。短暂确认方向后转开视线，拉开距离，优先保住退路和队友。', steps: ['先听笑声或观察屏幕边缘提示，不要把镜头锁死在目标上。', '短暂确认方向后转开视线，向队友和 truck 方向移动。', '放下大件，保持门口、拐角和回程路线畅通。', '受伤后不要单独深入，等队友报点或从另一侧绕行。', '用当前版本复测触发距离、伤害和 Strength 影响，再更新数值。'], mistakes: '为了确认怪物而持续盯着看；带着大件在狭窄区停留；把社区伤害数字当成当前版本结论。', risk: '不同资料对触发秒数、伤害和碰撞处理说法不一，正文只保留行为建议。', sources: [{ label: '怪物指南', href: 'https://www.switchbladegaming.com/co-op-games/repo/all-monsters-guide-2026/' }, { label: '怪物档案', href: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3582710295' }] },
  { id: 'P0-9', tag: '怪物', title: 'Rugrat：先保护 valuables', summary: '发现它靠近贵重物时，先移动货物，再决定是否追。', lead: 'Rugrat 会抢 valuables 并把物品扔开。发现它靠近贵重物时先抢救物品、拉开怪物与队友的投掷线，分散站位；不要为了追怪丢掉整趟收益。', steps: ['看到 Rugrat 靠近贵重物，先报点并停止继续搬入危险区。', '优先把已发现的 valuables 移到车边、角落或队友可接力的位置。', '不要多人挤在同一条投掷线，队伍分成搬运和看路两组。', '货物安全后再判断绕行、控制或反制；追怪不是默认目标。', '记录物品被扔后的损失和当前 Strength/多人合抓表现。'], mistakes: '先追怪后救货；队友站成一条线；把大件放在怪物和回程之间。', risk: '投掷时间、伤害和多人处理方式可能变动，发布时保留复测条件。', sources: [{ label: '怪物指南', href: 'https://www.switchbladegaming.com/co-op-games/repo/all-monsters-guide-2026/' }, { label: '中文攻略整理', href: 'https://www.ggkuai.com/client/treasure-box/guguai/101451.html' }] },
  { id: 'P0-10', tag: '商店', title: '商店先买能提高成功率的东西', summary: '生存、搬运、控制、保值四类物品，按当前失败原因取舍。', lead: '第一笔钱解决下一趟最可能的失败：缺体力/搬不动选 Stamina/Strength；易倒地选 Health；够不到选 Range；大件易碎再看 Feather 或 Indestructible。', steps: ['先看上一局的失败原因：体力、搬运、受伤、控制还是物品损失。', '生存类：Stamina/Health 让下一趟有更多容错。', '搬运类：Strength/Range 让主要搬运者更快、更少贴近危险。', '控制与保值类：Tranq 等控制工具处理挡路怪，Feather/Indestructible 保护脆弱重货。', '预算有限时只买一项，下一趟验证收益；不要因为“看起来强”就空买。'], mistakes: '把 tier list 当成无条件购买顺序；忽略库存随机；买了工具却没有队友负责使用。', risk: '商店价格和随机库存随版本变化，本站只发布选择逻辑，不承诺固定价格。', sources: [{ label: '商店指南', href: 'https://www.repo-game.org/en/repogame-tier-list' }, { label: '物品说明', href: 'https://twinfinite.net/guides/all-items-in-repo-how-use-them/' }] },
];

const navItems = [
  { label: 'P0 首屏', icon: Grid2X2 },
  { label: '详细攻略', icon: BookOpen },
  { label: '升级与力量', icon: Swords },
  { label: '怪物速查', icon: Shield },
  { label: '来源与版本', icon: Trophy },
];

function BrandMark() {
  return <div className="flex items-center gap-3"><div className="relative flex h-9 w-9 items-center justify-center rounded-[10px] bg-[#ff7043] text-[#111417] shadow-[0_0_24px_rgba(255,112,67,0.28)]"><span className="absolute left-[8px] top-[7px] h-[11px] w-[11px] rounded-[3px] border-[2px] border-[#111417]" /><span className="absolute bottom-[7px] right-[7px] h-[10px] w-[10px] rotate-45 border-[2px] border-[#111417]" /></div><div><div className="font-mono text-[15px] font-bold tracking-[0.22em] text-white">RUNBACK</div><div className="mt-0.5 text-[8px] font-semibold uppercase tracking-[0.24em] text-[#84909b]">R.E.P.O. 攻略站</div></div></div>;
}

export default function Home() {
  const [activeNav, setActiveNav] = useState('P0 首屏');
  const [mobileNav, setMobileNav] = useState(false);
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState('P0-1');
  const [saved, setSaved] = useState(false);
  const selected = guides.find((guide) => guide.id === selectedId) ?? guides[0];
  const filteredGuides = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    if (!normalized) return guides;
    return guides.filter((guide) => `${guide.id} ${guide.tag} ${guide.title} ${guide.summary}`.toLowerCase().includes(normalized));
  }, [query]);

  const jumpToGuide = (id: string) => {
    setSelectedId(id);
    document.getElementById('guide-detail')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return <main className="min-h-screen bg-[#111417] text-[#f1f3f4] selection:bg-[#ff7043] selection:text-[#111417]">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_70%_0%,rgba(255,112,67,0.09),transparent_28%),radial-gradient(circle_at_0%_90%,rgba(74,125,153,0.08),transparent_30%)]" />
    <div className="relative mx-auto flex min-h-screen max-w-[1600px]">
      <aside className={`fixed inset-y-0 left-0 z-30 w-[246px] border-r border-white/[0.07] bg-[#111417] px-7 py-7 transition-transform lg:sticky lg:top-0 lg:flex lg:h-screen lg:translate-x-0 lg:flex-col ${mobileNav ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="mb-12 flex items-center justify-between lg:block"><BrandMark /><button aria-label="关闭导航" onClick={() => setMobileNav(false)} className="rounded-lg p-2 text-[#84909b] hover:bg-white/5 hover:text-white lg:hidden"><X size={20} /></button></div>
        <div className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#64717c]">攻略目录</div>
        <nav className="space-y-1">{navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActiveNav(label); setMobileNav(false); }} className={`group flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] transition ${activeNav === label ? 'bg-white/[0.08] text-white' : 'text-[#8a959e] hover:bg-white/[0.04] hover:text-white'}`}><Icon size={17} strokeWidth={activeNav === label ? 2.4 : 1.8} className={activeNav === label ? 'text-[#ff7043]' : 'text-[#64717c] group-hover:text-[#aeb8c0]'} /><span>{label}</span></button>)}</nav>
        <div className="my-9 h-px bg-white/[0.07]" /><div className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#64717c]">快速动作</div>
        <div className="space-y-1"><button onClick={() => document.getElementById('guide-list')?.scrollIntoView({ behavior: 'smooth' })} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-[13px] text-[#8a959e] transition hover:bg-white/[0.04] hover:text-white"><Users size={17} className="text-[#64717c]" /> 浏览全部 P0 <span className="ml-auto font-mono text-[10px] text-[#64717c]">10</span></button><button onClick={() => setSaved(!saved)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-[13px] text-[#8a959e] transition hover:bg-white/[0.04] hover:text-white"><BookOpen size={17} className="text-[#64717c]" /> {saved ? '已保存本次攻略' : '保存首局路线'} <span className="ml-auto text-[#64717c]">{saved ? '✓' : '＋'}</span></button></div>
        <div className="mt-auto rounded-2xl border border-white/[0.07] bg-white/[0.035] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#64717c]">版本基准</span><span className="flex items-center gap-1.5 text-[10px] font-semibold text-[#79c7a0]"><span className="h-1.5 w-1.5 rounded-full bg-[#79c7a0]" /> 已标注</span></div><div className="font-mono text-[13px] font-bold text-white">v0.4.0 · P0 攻略</div><p className="mt-1 text-[11px] leading-relaxed text-[#7c8790]">社区资料中的固定数值会标记为待复测。</p></div>
      </aside>

      <section className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-white/[0.07] bg-[#111417]/90 px-5 backdrop-blur-xl sm:px-9"><button aria-label="打开导航" onClick={() => setMobileNav(true)} className="rounded-lg p-2 text-[#84909b] hover:bg-white/5 hover:text-white lg:hidden"><Menu size={21} /></button><div className="relative hidden w-full max-w-[410px] sm:block"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#64717c]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索 P0、升级、怪物……" className="h-10 w-full rounded-xl border border-white/[0.08] bg-white/[0.04] pl-10 pr-4 text-[12px] text-white outline-none placeholder:text-[#66727c] focus:border-[#ff7043]/60" /></div><div className="ml-auto flex items-center gap-4"><div className="hidden items-center gap-2 text-[12px] font-medium text-[#89949c] md:flex"><Crosshair size={16} className="text-[#ff8662]" /> 可发布攻略</div><div className="h-7 w-px bg-white/[0.08]" /><span className="rounded-full border border-white/[0.09] bg-white/[0.04] px-3 py-2 font-mono text-[10px] text-[#c7ced3]">P0 / 10 篇</span></div></header>

        <div className="mx-auto max-w-[1250px] px-5 pb-16 pt-8 sm:px-9 lg:px-12 lg:pt-11"><div className="mb-10 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="mb-4 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-[#ff8060]"><Flame size={13} /> R.E.P.O. / P0 Field Guide</div><h1 className="max-w-[720px] text-4xl font-semibold tracking-[-0.04em] text-white sm:text-[52px] sm:leading-[1.02]">先把这一趟<br /><span className="text-[#ff7043]">安全带回车。</span></h1><p className="mt-5 max-w-[620px] text-[14px] leading-relaxed text-[#8d989f]">一站式 P0 攻略：首局流程、配额、撤离、升级、力量断点和怪物处理。先看 30 秒答案，再按需展开细节。</p></div><div className="flex items-center gap-2 rounded-xl border border-[#79c7a0]/20 bg-[#79c7a0]/[0.06] px-3 py-2 text-[11px] font-medium text-[#9fd7ba]"><span className="h-2 w-2 rounded-full bg-[#79c7a0]" /> 首屏答案全部 ≤ 30 秒 <span className="text-[#5f8f78]">·</span> v0.4.0 基准</div></div>

          <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.75fr)]"><article className="relative min-h-[340px] overflow-hidden rounded-2xl border border-white/[0.09] bg-[#192126] p-7 sm:p-9"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(255,112,67,0.2),transparent_34%),linear-gradient(120deg,#192126,#1b252b)]" /><div className="absolute right-8 top-8 font-mono text-[86px] font-bold leading-none text-white/[0.04]">P0</div><div className="relative flex h-full flex-col justify-between"><div><div className="mb-8 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#ff8662]"><Zap size={14} fill="currentColor" /> 30 秒首屏答案</div><h2 className="max-w-[510px] text-3xl font-semibold leading-[1.08] tracking-[-0.03em] text-white sm:text-[40px]">第一次玩，<br /><span className="text-[#ff7043]">先完成一趟。</span></h2><p className="mt-4 max-w-[540px] text-[13px] leading-relaxed text-[#abb4ba]">做 Tutorial → 出车推 C.A.R.T. → 搬近处易控物品 → 完整放入 extraction point → 达到 quota → 回 truck → 按失败原因买升级。</p></div><div className="mt-8 flex flex-wrap items-center gap-3"><button onClick={() => jumpToGuide('P0-1')} className="flex items-center gap-2 rounded-lg bg-[#ff7043] px-4 py-2.5 text-[12px] font-bold text-[#16191b] transition hover:bg-[#ff8965]">阅读首局步骤 <ArrowUpRight size={15} /></button><span className="text-[11px] text-[#89949c]">先交付，再贪多</span></div></div></article>

            <article className="rounded-2xl border border-white/[0.09] bg-[#161b1f] p-6 sm:p-7"><div className="mb-6 flex items-start justify-between"><div><div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#74818a]">Quick reference</div><h2 className="text-xl font-semibold tracking-[-0.02em] text-white">失败原因 → 解法</h2></div><Trophy size={18} className="text-[#ff8662]" /></div><div className="space-y-3"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#ff7043] font-mono text-[13px] font-bold text-[#15191b]">搬</div><div><div className="text-[12px] font-semibold text-[#d6dcdf]">搬不动 / 太慢</div><div className="text-[10px] text-[#66737d]">Strength 或 Stamina</div></div></div><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#79c7a0] font-mono text-[13px] font-bold text-[#15191b]">活</div><div><div className="text-[12px] font-semibold text-[#d6dcdf]">总被击倒</div><div className="text-[10px] text-[#66737d]">Health 或先改路线</div></div></div><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#4a7d99] font-mono text-[13px] font-bold text-white">怪</div><div><div className="text-[12px] font-semibold text-[#d6dcdf]">怪物挡路</div><div className="text-[10px] text-[#66737d]">报点、停搬、留退路</div></div></div></div><div className="mt-6 border-t border-white/[0.07] pt-4 text-[11px] text-[#79858e]">数值型结论请先看<span className="font-semibold text-[#b8c0c5]">版本风险</span>，再决定是否复测。</div></article></div>

          <section id="guide-list" className="mt-9"><div className="mb-5 flex items-end justify-between"><div><div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#74818a]">P0 Index</div><h2 className="text-2xl font-semibold tracking-[-0.03em] text-white">先看哪一篇</h2></div><span className="text-[11px] text-[#66737d]">{filteredGuides.length} / {guides.length} 篇</span></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredGuides.map((guide) => <button key={guide.id} onClick={() => jumpToGuide(guide.id)} className={`group flex min-h-[154px] flex-col rounded-xl border p-4 text-left transition hover:-translate-y-0.5 ${selectedId === guide.id ? 'border-[#ff7043]/50 bg-[#ff7043]/[0.08]' : 'border-white/[0.07] bg-[#161b1f] hover:border-white/[0.16] hover:bg-[#1a2126]'}`}><div className="mb-5 flex items-center justify-between"><span className="font-mono text-[11px] font-bold text-[#ff8662]">{guide.id}</span><ArrowUpRight size={16} className="text-[#52606a] transition group-hover:text-[#ff8662]" /></div><div className="mb-1 text-[9px] font-bold tracking-[0.18em] text-[#74818a]">{guide.tag}</div><h3 className="text-[14px] font-semibold text-[#e5e9eb] group-hover:text-white">{guide.title}</h3><p className="mt-2 line-clamp-2 text-[11px] leading-relaxed text-[#6f7b84]">{guide.summary}</p><span className="mt-auto pt-3 text-[10px] font-semibold text-[#ff8662]">查看步骤 <ChevronRight size={12} className="inline" /></span></button>)}</div></section>

          <section id="guide-detail" className="mt-10 scroll-mt-24 rounded-2xl border border-white/[0.09] bg-[#161b1f] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 border-b border-white/[0.07] pb-6 sm:flex-row sm:items-start"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#ff8662]"><span className="font-mono">{selected.id}</span><span className="text-[#59656d]">/</span><span>{selected.tag}</span></div><h2 className="max-w-[760px] text-2xl font-semibold tracking-[-0.03em] text-white sm:text-3xl">{selected.title}</h2><p className="mt-3 max-w-[800px] text-[13px] leading-relaxed text-[#aeb7bc]">{selected.lead}</p></div><button onClick={() => setSaved(!saved)} className={`flex shrink-0 items-center justify-center gap-2 rounded-lg border px-3 py-2 text-[11px] font-bold transition ${saved ? 'border-[#79c7a0]/40 bg-[#79c7a0]/10 text-[#9fd7ba]' : 'border-white/[0.1] text-[#abb5ba] hover:border-[#ff7043]/50 hover:text-white'}`}><BookOpen size={14} /> {saved ? '已保存' : '保存攻略'}</button></div><div className="mt-7 grid gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><div><h3 className="mb-4 text-[11px] font-bold uppercase tracking-[0.18em] text-[#74818a]">详细步骤</h3><ol className="space-y-3">{selected.steps.map((step, index) => <li key={step} className="flex gap-3 rounded-xl border border-white/[0.06] bg-white/[0.025] p-4"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-[#ff7043]/15 font-mono text-[11px] font-bold text-[#ff8662]">{String(index + 1).padStart(2, '0')}</span><span className="text-[13px] leading-relaxed text-[#c7ced3]">{step}</span></li>)}</ol></div><aside className="space-y-5"><div className="rounded-xl border border-[#ff7043]/20 bg-[#ff7043]/[0.05] p-4"><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#ff8662]">易错点</div><p className="text-[12px] leading-relaxed text-[#c4cbd0]">{selected.mistakes}</p></div><div className="rounded-xl border border-[#79c7a0]/20 bg-[#79c7a0]/[0.05] p-4"><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#9fd7ba]">版本提示</div><p className="text-[12px] leading-relaxed text-[#c4cbd0]">{selected.risk}</p></div><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#74818a]">来源</div><div className="space-y-2">{selected.sources.map((source) => <a key={source.href} href={source.href} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-white/[0.07] px-3 py-2 text-[11px] text-[#aeb7bc] transition hover:border-[#ff7043]/40 hover:text-white">{source.label}<ArrowUpRight size={13} className="text-[#ff8662]" /></a>)}</div></div></aside></div></section>

          <footer className="mt-14 flex flex-col gap-3 border-t border-white/[0.07] pt-5 text-[10px] text-[#59656d] sm:flex-row sm:items-center sm:justify-between"><div>RUNBACK 是面向 R.E.P.O. 玩家的 P0 攻略站。</div><div className="flex gap-4"><span>资料基准 v0.4.0</span><span className="text-[#71808a]">社区资料仅作二创参考</span></div></footer>
        </div>
      </section>
    </div>
  </main>;
}
