export type RepoEnemy = {
  id: string;
  name: string;
  alias: string;
  tier: 'DL1' | 'DL2' | 'DL2*' | 'DL3';
  threat: 1 | 2 | 3 | 4 | 5;
  trigger: string;
  tell: string;
  behavior: string;
  counter: string;
  decision: 'Avoid' | 'Clear if blocking' | 'Fight with setup';
  image: string;
  source: string;
  note?: string;
};

const monsterGuideSource = 'https://itemlevel.net/repo-all-monsters-guide-how-to-beat-them/';

export const repoEnemies: RepoEnemy[] = [
  { id: 'peeper', name: 'Peeper', alias: 'Eye', tier: 'DL1', threat: 2, trigger: 'Sight / gaze lock', tell: 'Ceiling eye opens and pulls your view upward.', behavior: 'It locks onto a player who looks at it for too long and drains health while the gaze is held.', counter: 'Break line of sight behind a solid object. Do not stop in the open to fight it.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/7sHzYtV3Dq.png', source: monsterGuideSource },
  { id: 'shadow-child', name: 'Shadow Child', alias: 'Shadow Child', tier: 'DL1', threat: 2, trigger: 'Sound cue + gaze', tell: 'A giggle and a dark child-shaped silhouette.', behavior: 'It blinks in and out, and prolonged eye contact can trigger a jump attack and knockback.', counter: 'Use a brief glance to locate it, then look away and keep a clear retreat lane.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/XOkFBqitHA.png', source: monsterGuideSource },
  { id: 'gnomes', name: 'Gnomes', alias: 'Gnome swarm', tier: 'DL1', threat: 2, trigger: 'Sight / group spawn', tell: 'Small creatures appear in a pack around loot.', behavior: 'They swarm players and valuables; a group can strip value from a cart faster than one gnome suggests.', counter: 'Protect the cart, split the pack, and throw or smash them before resuming the carry.', decision: 'Clear if blocking', image: 'https://itemlevel.net/wp-content/uploads/2025/03/Uj5WEKRkwc.png', source: monsterGuideSource },
  { id: 'apex-predator', name: 'Apex Predator', alias: 'Yellow Duck', tier: 'DL1', threat: 5, trigger: 'Touch or damage', tell: 'A harmless yellow duck follows the team.', behavior: 'Picking it up or damaging it transforms it into a fast chaser for a short window.', counter: 'Do not touch it. If removal is necessary, use a tested environment or Duck Bucket counter with a clear exit.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/7VX4sLkIiM.png', source: monsterGuideSource, note: 'The duck’s trigger is stable across sources; exact chase timing and reward are version-sensitive.' },
  { id: 'spewer', name: 'Spewer', alias: 'Spewer', tier: 'DL1', threat: 3, trigger: 'Proximity / latch', tell: 'Fast airborne movement and a wet gurgling cue.', behavior: 'It can latch onto a player and create vomit that damages nearby players, items, or entities.', counter: 'Keep distance and interrupt before the latch. If attached, avoid teammates and valuables until the effect is broken.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/EPFfPYvmoJ.png', source: monsterGuideSource },
  { id: 'tick', name: 'Tick', alias: 'Beam parasite', tier: 'DL1', threat: 2, trigger: 'Nearby grab / beam contact', tell: 'A small parasite launches while the carrier is handling an object.', behavior: 'It drains health while attached, then becomes harmless after feeding; a fed Tick may create a healing opportunity.', counter: 'Drop the valuable, create space, and do not force a carry through the contact zone.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02205224/Tick-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'heart-hugger', name: 'Heart Hugger', alias: 'Heart Hugger', tier: 'DL1', threat: 4, trigger: 'Proximity / pull field', tell: 'A pink heart and a gas cloud pull the player inward.', behavior: 'The pull drags a target toward the heart for a damaging close-range sequence.', counter: 'Stay outside the cloud. In co-op, keep pulling the victim away while another player interrupts from a safe angle.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02205825/Heart-Hugger-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'rugrat', name: 'Rugrat', alias: 'Baby monster', tier: 'DL2', threat: 4, trigger: 'Sight / valuables', tell: 'A small enemy reaches for nearby valuables.', behavior: 'It steals items and throws them as projectiles, turning fragile loot into a damage source.', counter: 'Move valuables out of reach, separate the team, and use ranged damage or a coordinated grab.', decision: 'Clear if blocking', image: 'https://itemlevel.net/wp-content/uploads/2025/03/hz7GwP3GP7.png', source: monsterGuideSource },
  { id: 'animal', name: 'Animal', alias: 'Animal', tier: 'DL2', threat: 1, trigger: 'Sight / charge', tell: 'Fast, erratic movement with a low-damage attack.', behavior: 'It charges the last known position and then runs unpredictably; multiple players can briefly control it.', counter: 'Sidestep after the lock, keep it away from the cart, or coordinate a quick melee clear.', decision: 'Fight with setup', image: 'https://itemlevel.net/wp-content/uploads/2025/03/SYaTXCRPpA.png', source: monsterGuideSource },
  { id: 'upscream', name: 'Upscream', alias: 'Upscream', tier: 'DL2', threat: 4, trigger: 'Sight / group spawn', tell: 'A wall- or ceiling-crawling creature grabs and screams.', behavior: 'The scream flings and stuns a player; groups can chain-stun a team before it recovers.', counter: 'Never let the group surround one player. Split angles, use heavy melee or Tranq, and finish quickly.', decision: 'Clear if blocking', image: 'https://itemlevel.net/wp-content/uploads/2025/03/RJmgvTBjKc.png', source: monsterGuideSource },
  { id: 'chef', name: 'Chef', alias: 'Frog', tier: 'DL2', threat: 3, trigger: 'Sight / leap wind-up', tell: 'It stops, faces the team, and telegraphs a knife leap.', behavior: 'It charges and leaps over low obstacles; a missed leap creates a short vulnerable window.', counter: 'Sidestep the leap, then either escape or punish the recovery with a ranged or melee hit.', decision: 'Fight with setup', image: 'https://itemlevel.net/wp-content/uploads/2025/03/t7sfkWxw2i.png', source: monsterGuideSource },
  { id: 'hidden', name: 'Hidden', alias: 'Invisible grabber', tier: 'DL2', threat: 4, trigger: 'Breathing / footsteps', tell: 'Heavy breathing, wet footsteps, dust, or foggy breath with no visible body.', behavior: 'It grabs and drags a player to a dangerous location; the threat is the destination, not just the grab.', counter: 'Call the audio cue, listen as a group, and use Tranq, tumbles, or a timed intercept to break the grab.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/tjTWGFb8OH.png', source: monsterGuideSource },
  { id: 'bowtie', name: 'Bowtie', alias: 'Screamer', tier: 'DL2', threat: 4, trigger: 'Sight / scream', tell: 'A large floating body begins a sustained scream.', behavior: 'The scream pushes players and objects, disables sprint and jump, and can lead into a fast charge.', counter: 'Wait outside the wave, use sturdy cover, or use Tranq/firearms while it is stationary.', decision: 'Clear if blocking', image: 'https://itemlevel.net/wp-content/uploads/2025/03/3yRapGKCzS.png', source: monsterGuideSource },
  { id: 'mentalist', name: 'Mentalist', alias: 'Alien', tier: 'DL2', threat: 4, trigger: 'Sight / gravity field', tell: 'Objects and players begin to float as the field builds.', behavior: 'It lifts a group and slams them down; clustering makes the same attack much worse.', counter: 'Spread out, break line of sight, and attack from a safe angle before the field completes.', decision: 'Clear if blocking', image: 'https://itemlevel.net/wp-content/uploads/2025/03/7hgjNIRXT9.png', source: monsterGuideSource },
  { id: 'bangers', name: 'Bangers', alias: 'Explosive trio', tier: 'DL2', threat: 5, trigger: 'Sight / fuse', tell: 'Fuse hiss, ignition sound, and a lit explosive charge.', behavior: 'They spawn in groups and charge after provocation; close explosions can instantly end a run.', counter: 'Spread out, throw or push one away, and use pits or empty space. Clear them for safety, not profit.', decision: 'Clear if blocking', image: 'https://itemlevel.net/wp-content/uploads/2025/03/OJl8ITfLfp.png', source: monsterGuideSource },
  { id: 'bella', name: 'Bella', alias: 'Tricycle', tier: 'DL2', threat: 3, trigger: 'Proximity / bell rings', tell: 'A tricycle bell repeats when the team lingers nearby.', behavior: 'It is passive until repeated bell rings, then becomes aggressive and faster.', counter: 'Back away before the ring count completes and wait for the route to calm down.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02205331/Bella-Tricycle-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'birthday-boy', name: 'Birthday Boy', alias: 'Balloon monster', tier: 'DL2', threat: 3, trigger: 'Balloon burst', tell: 'Balloons are scattered through the room or route.', behavior: 'A popped balloon can identify the player and start a chase; objects and doors can pop them too.', counter: 'Do not pop balloons. If the map is saturated, consider a controlled clear only with a retreat lane.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02205000/Birthday-Boy-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'elsa', name: 'Elsa', alias: 'Dog', tier: 'DL2', threat: 4, trigger: 'Proximity / attention', tell: 'A friendly dog remains in the route and waits for interaction.', behavior: 'Ignoring it for too long can trigger a transformation and a fast chase with heavy wall impact risk.', counter: 'Give the interaction it asks for when safe, or use a pit/stun plan after transformation; open rooms are safer.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02205101/Elsa-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'oogly', name: 'Oogly', alias: 'Flying patrol', tier: 'DL2', threat: 4, trigger: 'Sight / ground circle', tell: 'A flying enemy projects a detection circle below itself.', behavior: 'Lingering inside the circle leads to a dive, grab, and throw, especially dangerous near pits.', counter: 'Leave the circle, use cover under objects, or choose ranged/stun tools instead of air melee.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02205912/Oogly-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'headgrab', name: 'Headgrab', alias: 'Grabber', tier: 'DL2', threat: 4, trigger: 'Sight / dead teammate', tell: 'A melee enemy closes in and may carry a fallen player’s head.', behavior: 'It swipes and dropkicks; attaching a head makes its attacks faster and gives the dead player its view.', counter: 'Reclaim the head to create a stun window, then disengage or finish it with a coordinated hit.', decision: 'Clear if blocking', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02210001/Headgrab-Grabber-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'headman', name: 'Headman', alias: 'Floating Head', tier: 'DL3', threat: 5, trigger: 'Sight / direct face contact', tell: 'Floating head, bite audio, and a corridor patrol.', behavior: 'A close bite creates heavy damage and knockback; a surprise face-to-face encounter is especially dangerous.', counter: 'Keep the light and camera off its face when the current build reacts, break line of sight around a corner, and never let it set the corridor.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/0WzOKWawdS.png', source: monsterGuideSource, note: 'Flashlight and gaze interactions are reported differently across versions; publish the current-client result with a patch tag.' },
  { id: 'robe', name: 'Robe', alias: 'Cloak', tier: 'DL3', threat: 5, trigger: 'Sight / face contact', tell: 'A silent stalker follows from behind or waits beyond a turn.', behavior: 'Looking directly at its face triggers an aggressive chase; hiding spots are checked more persistently than with smaller threats.', counter: 'Do not face it. Pass behind it, break sight with a door, or use a Duct Tape Grenade only when the route demands it.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/N2Cu75TKk2.png', source: monsterGuideSource },
  { id: 'huntsman', name: 'Huntsman', alias: 'Blind shotgun hunter', tier: 'DL3', threat: 5, trigger: 'Sound only', tell: 'Shotgun audio, patrol pressure, and unusual quiet around the route.', behavior: 'It cannot see but hears footsteps, voices, mic audio, item handling, and other disturbances across a large radius.', counter: 'Crouch-walk, use push-to-talk or mute, bait sound away from the carrier, and do not melee it.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/wtZXlnYPQm.png', source: monsterGuideSource },
  { id: 'reaper', name: 'Reaper', alias: 'Hay monster', tier: 'DL3', threat: 5, trigger: 'Sight only', tell: 'Loud rustling footsteps and a fast visual lock.', behavior: 'It is deaf but charges quickly when it sees a player, then can lose the target after a clean corner.', counter: 'Run first, break line of sight, and avoid wasting time on crouch silence. Use cover, a turn, or a tested stun.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/DPAE4alnVo.png', source: monsterGuideSource },
  { id: 'clown', name: 'Clown', alias: 'Beamer', tier: 'DL3', threat: 5, trigger: 'Sight / laser charge', tell: 'Heavy steps, laughter, and a horizontal beam wind-up.', behavior: 'The laser sweeps horizontally and can delete players or valuables; a close kick is the fallback attack.', counter: 'Use solid cover, crouch or jump only after the sweep begins, and keep loot away from the line of fire.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/oxVKvPEwTS.png', source: monsterGuideSource },
  { id: 'trudge', name: 'Trudge', alias: 'Mace / suction monster', tier: 'DL3', threat: 5, trigger: 'Proximity / ground shake', tell: 'Grinding mace audio and ground vibration through walls.', behavior: 'It is slow but can pull players or heavy valuables into a lethal close-range strike; crouching behavior is patch-sensitive.', counter: 'Keep open space, park large loot outside the pull lane, and wait for it to pass instead of fighting in a choke point.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/6IPKBw6hOI.png', source: monsterGuideSource, note: 'Official v0.4.4 notes changed how Trudge handles larger valuables. Recheck crouch detection and suction behavior after updates.' },
  { id: 'loom', name: 'Loom', alias: 'Shadow hands', tier: 'DL3', threat: 5, trigger: 'Sight / cross-room lock', tell: 'Shadowy hands appear around the screen after it selects a target.', behavior: 'It can track across rooms and clap for heavy damage; repeated misses may create the only reliable escape window.', counter: 'Keep moving around sturdy geometry to force misses, then leave. Do not trust furniture as a guaranteed shield.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02210149/Loom-Shadow-Monster-in-REPO.png', source: monsterGuideSource },
  { id: 'gambit', name: 'Gambit', alias: 'Spinny / roulette', tier: 'DL2*', threat: 4, trigger: 'Sight / proximity / grab', tell: 'A roulette-wheel body closes in rather than attacking immediately.', behavior: 'It grabs a player and forces a random wheel result; interrupting it carelessly can hurt the grabbed teammate.', counter: 'Do not let it isolate a player. Communicate before interrupting, and treat the wheel result as a risk rather than a reward plan.', decision: 'Avoid', image: 'https://itemlevel.net/wp-content/uploads/2025/03/02205428/Gambit-Monster-in-REPO.png', source: monsterGuideSource, note: 'Spawn tier is inconsistent across community and encyclopedia sources; the site labels it DL2* until the current client is tested.' },
  { id: 'cleanup-crew', name: 'Cleanup Crew', alias: 'Bombthrower', tier: 'DL3', threat: 5, trigger: 'Sight + sound', tell: 'An explosive head is thrown and keeps tracking the player.', behavior: 'The projectile can bounce, explode, and leave a damaging area; the death drop can still be dangerous.', counter: 'Take sharp side turns, throw the head sideways when possible, keep distance, and wait before collecting the orb.', decision: 'Avoid', image: 'https://media.itemlevel.net/wp-content/uploads/2025/03/02210110/Cleanup-Crew-Monster-in-REPO.png', source: monsterGuideSource },
];
