// Player-facing Artifact fields only. Generated by the offline normalizer.
import type { SephiriaRecord } from './sephiria-wiki-data';

export const sephiriaArtifactFacts: Record<string, Pick<SephiriaRecord, 'rarity' | 'effectCurrent' | 'mechanicCurrent' | 'artifactCategories' | 'artifactEffectLabel' | 'currentValues' | 'effectsByLevel'>> = {
  "ART-01": {
    "rarity": "Rare",
    "effectCurrent": "Increases the Critical Chance of ice attacks by +5% (also applies to Companion damage)\nMP Regeneration -9",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Glacier"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Increases the Critical Chance of ice attacks by +5% (also applies to Companion damage)\nMP Regeneration -9",
      "Increases the Critical Chance of ice attacks by +10% (also applies to Companion damage)\nMP Regeneration -6",
      "Increases the Critical Chance of ice attacks by +15% (also applies to Companion damage)\nMP Regeneration -3",
      "Increases the Critical Chance of ice attacks by +20% (also applies to Companion damage)\nMP Regeneration +0"
    ]
  },
  "ART-02": {
    "rarity": "Advanced",
    "effectCurrent": "Companion placed in the same Row of the Inventory deal Chaos damage",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Companion"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-03": {
    "rarity": "Rare",
    "effectCurrent": "When Normal Attack hits, deal additional damage with a 80% chance.\n[Damage: Physical Damage 40% + Cold Damage 80% (considered as Normal Attack damage)]",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Glacier",
      "Sturdy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "When Normal Attack hits, deal additional damage with a 80% chance.\n[Damage: Physical Damage 40% + Cold Damage 80% (considered as Normal Attack damage)]",
      "When Normal Attack hits, deal additional damage with a 120% chance.\n[Damage: Physical Damage 75% + Cold Damage 150% (considered as Normal Attack damage)]",
      "When Normal Attack hits, deal additional damage with a 180% chance.\n[Damage: Physical Damage 125% + Cold Damage 250% (considered as Normal Attack damage)]"
    ]
  },
  "ART-04": {
    "rarity": "Advanced",
    "effectCurrent": "Launch 1 chakrams that periodically attack nearby enemies\n[Damage: 10 (Lightning Damage50%)]\nOn Chakram hit, inflict Electrocution with a 10% chance.",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Magitech"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Launch 1 chakrams that periodically attack nearby enemies\n[Damage: 10 (Lightning Damage50%)]\nOn Chakram hit, inflict Electrocution with a 10% chance.",
      "Launch 2 chakrams that periodically attack nearby enemies\n[Damage: 10x2 (Lightning Damage50%)]\nOn Chakram hit, inflict Electrocution with a 10% chance.",
      "Launch 2 chakrams that periodically attack nearby enemies\n[Damage: 16x2 (Lightning Damage80%)]\nOn Chakram hit, inflict Electrocution with a 10% chance.",
      "Launch 3 chakrams that periodically attack nearby enemies\n[Damage: 16x3 (Lightning Damage80%)]\nOn Chakram hit, inflict Electrocution with a 10% chance.",
      "Launch 3 chakrams that periodically attack nearby enemies\n[Damage: 22x3 (Lightning Damage110%)]\nOn Chakram hit, inflict Electrocution with a 30% chance."
    ]
  },
  "ART-05": {
    "rarity": "Advanced",
    "effectCurrent": "Max HP +5\nEvasion -5",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Guardian"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Max HP +5\nEvasion -5",
      "Max HP +10\nEvasion -4",
      "Max HP +15\nEvasion -3",
      "Max HP +20\nEvasion -2"
    ]
  },
  "ART-06": {
    "rarity": "Legendary",
    "effectCurrent": "Weapon Damage +2%\nAttack Speed -20%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Sturdy"
    ],
    "currentValues": [
      {
        "label": "Weapon Damage",
        "values": [
          "+2%",
          "+4%",
          "+6%",
          "+9%",
          "+12%",
          "+15%",
          "+20%"
        ]
      },
      {
        "label": "Attack Speed",
        "values": [
          "-20%",
          "-20%",
          "-20%",
          "-10%",
          "-5%",
          "-5%",
          "0%"
        ]
      }
    ],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-07": {
    "rarity": "Legendary",
    "effectCurrent": "Special Attack Damage +10%\nDash Recovery Speed +5%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Wind Song"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-08": {
    "rarity": "Legendary",
    "effectCurrent": "Grimoire Haste +40\nCritical Damage +8%\nReduce MP Cost of Grimoire +5%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Academy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Grimoire Haste +40\nCritical Damage +8%\nReduce MP Cost of Grimoire +5%",
      "Grimoire Haste +60\nCritical Damage +14%\nReduce MP Cost of Grimoire +5%",
      "Grimoire Haste +80\nCritical Damage +20%\nReduce MP Cost of Grimoire +10%"
    ]
  },
  "ART-09": {
    "rarity": "Rare",
    "effectCurrent": "Increases the Grimoire Haste of the Grimoire in the right slot by +60%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Academy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Increases the Grimoire Haste of the Grimoire in the right slot by +60%",
      "Increases the Grimoire Haste of the Grimoire in the right slot by +100%",
      "Increases the Grimoire Haste of the Grimoire in the right slot by +140%"
    ]
  },
  "ART-10": {
    "rarity": "Advanced",
    "effectCurrent": "Thorns +150%\nDefense +1",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Guardian"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Thorns +150%\nDefense +1",
      "Thorns +300%\nDefense +2",
      "Thorns +450%\nDefense +3"
    ]
  },
  "ART-11": {
    "rarity": "Legendary",
    "effectCurrent": "Automatically reloads 1 shot every 0.75 seconds (up to 7)",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Frost Relic"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-12": {
    "rarity": null,
    "effectCurrent": null,
    "mechanicCurrent": null,
    "artifactCategories": [],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-13": {
    "rarity": "Rare",
    "effectCurrent": "Attack Speed +4%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Planet",
      "Wind Song"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Attack Speed +4%",
      "Attack Speed +8%",
      "Attack Speed +12%\nEach Weapon Attack speeds up the attack cycle of planets"
    ]
  },
  "ART-14": {
    "rarity": "Rare",
    "effectCurrent": "Gain Grimoire Damage 1% per 5 Evasion\nAccelerate all Grimoire cooldowns by 5% upon successful Evasion",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Shadow",
      "Academy"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Base effect"
  },
  "ART-15": {
    "rarity": "Rare",
    "effectCurrent": "Fire an ice projectile at enemies afflicted with Frostbite every 0.5 sec\nThis damage is not affected by Frost Touch\nAttack Speed +2%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Glacier",
      "Wind Song"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-16": {
    "rarity": "Rare",
    "effectCurrent": "On Planet Attack hit, damage increases in proportion to Burn tick damage\nThe higher the Artifact grade, the greater the increase\nCommon: Burn  1-tick damage\nAdvanced : Burn  2-tick damage\nRare : Burn  3-tick damage\nLegendary : Burn  4-tick damage",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Planet",
      "Ember"
    ],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-17": {
    "rarity": "Rare",
    "effectCurrent": "Defense +3",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Guardian"
    ],
    "currentValues": [
      {
        "label": "Defense",
        "values": [
          "+3",
          "+6",
          "+9"
        ]
      }
    ],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-18": {
    "rarity": "Rare",
    "effectCurrent": "Gain the following effect for every 10 Defense\nFire Damage +1\nCold Damage +1\nLightning Damage +1",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Guardian",
      "Academy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Gain the following effect for every 10 Defense\nFire Damage +1\nCold Damage +1\nLightning Damage +1",
      "Gain the following effect for every 10 Defense\nFire Damage +1\nCold Damage +1\nLightning Damage +1",
      "Gain the following effect for every 10 Defense\nFire Damage +2\nCold Damage +2\nLightning Damage +2",
      "Gain the following effect for every 10 Defense\nFire Damage +3\nCold Damage +3\nLightning Damage +3"
    ]
  },
  "ART-19": {
    "rarity": "Legendary",
    "effectCurrent": "When Electrocution is applied, apply Enhanced Electrocution with a 15% chance\nLightning Damage +2",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Magitech"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "When Electrocution is applied, apply Enhanced Electrocution with a 15% chance\nLightning Damage +2",
      "When Electrocution is applied, apply Enhanced Electrocution with a 30% chance\nLightning Damage +4",
      "When Electrocution is applied, apply Enhanced Electrocution with a 45% chance\nLightning Damage +6",
      "When Electrocution is applied, apply Enhanced Electrocution with a 60% chance\nLightning Damage +8"
    ]
  },
  "ART-20": {
    "rarity": "Advanced",
    "effectCurrent": "Active Artifact (Cooldown: 6 seconds)\nFire 1 elemental bombs dealing 100% of the highest elemental damage",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Elemental"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Active Artifact (Cooldown: 6 seconds)\nFire 1 elemental bombs dealing 100% of the highest elemental damage",
      "Active Artifact (Cooldown: 6 seconds)\nFire 2 elemental bombs dealing 150% of the highest elemental damage",
      "Active Artifact (Cooldown: 6 seconds)\nFire 3 elemental bombs dealing 200% of the highest elemental damage",
      "Active Artifact (Cooldown: 6 seconds)\nFire 4 elemental bombs dealing 250% of the highest elemental damage"
    ]
  },
  "ART-21": {
    "rarity": null,
    "effectCurrent": null,
    "mechanicCurrent": null,
    "artifactCategories": [],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-22": {
    "rarity": "Legendary",
    "effectCurrent": "Summon Mole Chief",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Companion"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Summon Mole Chief",
      "Summon Mole Chief",
      "Summon Mole Chief",
      "Summon Mole Chief",
      "Summon Mole Chief"
    ]
  },
  "ART-23": {
    "rarity": "Rare",
    "effectCurrent": null,
    "mechanicCurrent": null,
    "artifactCategories": [],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-24": {
    "rarity": "Rare",
    "effectCurrent": null,
    "mechanicCurrent": null,
    "artifactCategories": [
      "Solar Blade"
    ],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-25": {
    "rarity": "Advanced",
    "effectCurrent": "Gain a combo of either Sturdy, Ember, Glacier, or Magitech depending on the row you are in\nDeals +2 elemental damage based on the granted combo.",
    "mechanicCurrent": null,
    "artifactCategories": [],
    "currentValues": [],
    "effectsByLevel": [
      "Gain a combo of either Sturdy, Ember, Glacier, or Magitech depending on the row you are in\nDeals +2 elemental damage based on the granted combo.",
      "Gain a combo of either Sturdy, Ember, Glacier, or Magitech depending on the row you are in\nDeals +4 elemental damage based on the granted combo.",
      "Gain a combo of either Sturdy, Ember, Glacier, or Magitech depending on the row you are in\nDeals +6 elemental damage based on the granted combo.",
      "Gain a combo of either Sturdy, Ember, Glacier, or Magitech depending on the row you are in\nDeals +8 elemental damage based on the granted combo."
    ]
  },
  "ART-26": {
    "rarity": "Rare",
    "effectCurrent": "Gain a 'Sonic Wave' stack each time Grimoire is cast every 0.8 seconds (up to 5 stacks)\nConsume all stacks with Weapon Attack to deal Chaos damage at the attack point (considered as Grimoire damage)\nDamage: Average damage of all elemental types 200% (Grimoire Haste 1 increases Tuning Fork damage by 1%)",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Academy",
      "Sturdy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Gain a 'Sonic Wave' stack each time Grimoire is cast every 0.8 seconds (up to 5 stacks)\nConsume all stacks with Weapon Attack to deal Chaos damage at the attack point (considered as Grimoire damage)\nDamage: Average damage of all elemental types 200% (Grimoire Haste 1 increases Tuning Fork damage by 1%)",
      "Gain a 'Sonic Wave' stack each time Grimoire is cast every 0.8 seconds (up to 5 stacks)\nConsume all stacks with Weapon Attack to deal Chaos damage at the attack point (considered as Grimoire damage)\nDamage: Average damage of all elemental types 250% (Grimoire Haste 1 increases Tuning Fork damage by 1%)",
      "Gain a 'Sonic Wave' stack each time Grimoire is cast every 0.8 seconds (up to 5 stacks)\nConsume all stacks with Weapon Attack to deal Chaos damage at the attack point (considered as Grimoire damage)\nDamage: Average damage of all elemental types 300% (Grimoire Haste 1 increases Tuning Fork damage by 1%)",
      "Gain a 'Sonic Wave' stack each time Grimoire is cast every 0.8 seconds (up to 5 stacks)\nConsume all stacks with Weapon Attack to deal Chaos damage at the attack point (considered as Grimoire damage)\nDamage: Average damage of all elemental types 350% (Grimoire Haste 1 increases Tuning Fork damage by 1%)",
      "Gain a 'Sonic Wave' stack each time Grimoire is cast every 0.8 seconds (up to 5 stacks)\nConsume all stacks with Weapon Attack to deal Chaos damage at the attack point (considered as Grimoire damage)\nDamage: Average damage of all elemental types 450% (Grimoire Haste 1 increases Tuning Fork damage by 1%)"
    ]
  },
  "ART-27": {
    "rarity": "Rare",
    "effectCurrent": "On Special Attack: Fury hit, deal +200% Fire damage to nearby enemies\nMax MP +6",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Ember"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "On Special Attack: Fury hit, deal +200% Fire damage to nearby enemies\nMax MP +6",
      "On Special Attack: Fury hit, deal +400% Fire damage to nearby enemies\nMax MP +12",
      "On Special Attack: Fury hit, deal +600% Fire damage to nearby enemies\nMax MP +20"
    ]
  },
  "ART-28": {
    "rarity": "Advanced",
    "effectCurrent": "Highest Elemental Damage +2\nMove Speed +2%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Elemental"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Highest Elemental Damage +2\nMove Speed +2%",
      "Highest Elemental Damage +3\nMove Speed +4%",
      "Highest Elemental Damage +4\nMove Speed +6%",
      "Highest Elemental Damage +6\nMove Speed +8%",
      "Highest Elemental Damage +8\nMove Speed +10%"
    ]
  },
  "ART-29": {
    "rarity": "Rare",
    "effectCurrent": "Highest Elemental Damage +2\nGrimoire Damage +3%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Elemental"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Highest Elemental Damage +2\nGrimoire Damage +3%",
      "Highest Elemental Damage +4\nGrimoire Damage +6%",
      "Highest Elemental Damage +6\nGrimoire Damage +9%",
      "Highest Elemental Damage +8\nGrimoire Damage +12%",
      "Highest Elemental Damage +10\nGrimoire Damage +15%"
    ]
  },
  "ART-30": {
    "rarity": "Advanced",
    "effectCurrent": "Critical Chance +2%\nHighest Elemental Damage +1",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Elemental"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Critical Chance +2%\nHighest Elemental Damage +1",
      "Critical Chance +4%\nHighest Elemental Damage +2",
      "Critical Chance +6%\nHighest Elemental Damage +3",
      "Critical Chance +8%\nHighest Elemental Damage +4"
    ]
  },
  "ART-31": {
    "rarity": null,
    "effectCurrent": null,
    "mechanicCurrent": null,
    "artifactCategories": [],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-32": {
    "rarity": "Advanced",
    "effectCurrent": "+4 Lightning Damage (Deactivated for 6 seconds upon hit)",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Magitech"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "+4 Lightning Damage (Deactivated for 6 seconds upon hit)",
      "+8 Lightning Damage (Deactivated for 6 seconds upon hit)",
      "+12 Lightning Damage (Deactivated for 6 seconds upon hit)"
    ]
  },
  "ART-33": {
    "rarity": "Advanced",
    "effectCurrent": "MP Regeneration +3\nFire Damage +1\nCold Damage +1\nLightning Damage +1\nPhysical Damage +1",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Lake",
      "Elemental"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "MP Regeneration +3\nFire Damage +1\nCold Damage +1\nLightning Damage +1\nPhysical Damage +1",
      "MP Regeneration +5\nFire Damage +1\nCold Damage +1\nLightning Damage +1\nPhysical Damage +1",
      "MP Regeneration +8\nFire Damage +2\nCold Damage +2\nLightning Damage +2\nPhysical Damage +2"
    ]
  },
  "ART-34": {
    "rarity": "Legendary",
    "effectCurrent": "Grimoire Damage +5%\nFinal MP +7%\nMP Regeneration +2",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Academy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Grimoire Damage +5%\nFinal MP +7%\nMP Regeneration +2",
      "Grimoire Damage +10%\nFinal MP +9%\nMP Regeneration +2",
      "Grimoire Damage +15%\nFinal MP +11%\nMP Regeneration +2",
      "Grimoire Damage +20%\nFinal MP +13%\nMP Regeneration +4",
      "Grimoire Damage +25%\nFinal MP +15%\nMP Regeneration +4",
      "Grimoire Damage +30%\nFinal MP +20%\nMP Regeneration +6"
    ]
  },
  "ART-35": {
    "rarity": "Rare",
    "effectCurrent": "When Frost Relic is activated, consume 4 MP to summon rotating ice swords (up to 5).",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Frost Relic",
      "Lake"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-36": {
    "rarity": "Advanced",
    "effectCurrent": "Weapon Damage +5%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Sturdy"
    ],
    "currentValues": [
      {
        "label": "Weapon Damage",
        "values": [
          "+5%",
          "+10%",
          "+15%"
        ]
      }
    ],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-37": {
    "rarity": "Advanced",
    "effectCurrent": "Weapon Damage +2%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Sturdy"
    ],
    "currentValues": [
      {
        "label": "Weapon Damage",
        "values": [
          "+2%",
          "+4%",
          "+6%"
        ]
      }
    ],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-38": {
    "rarity": "Common",
    "effectCurrent": "On a successful Special Attack: Parry, fires a sword spirit at the nearest enemy\n[Damage: 250% of Highest Elemental Damage as Chaos damage]\nSucceed at Special Attack: Parry 40 times to transform into Duelist's Epaulette",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Sturdy"
    ],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-39": {
    "rarity": "Advanced",
    "effectCurrent": "Highest Elemental Damage +2\nReach 140% Move Speed to transform into Resonance Stone",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Elemental"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Highest Elemental Damage +2\nReach 140% Move Speed to transform into Resonance Stone",
      "Highest Elemental Damage +4\nReach 140% Move Speed to transform into Resonance Stone",
      "Highest Elemental Damage +6\nReach 140% Move Speed to transform into Resonance Stone",
      "Highest Elemental Damage +8\nReach 140% Move Speed to transform into Resonance Stone"
    ]
  },
  "ART-40": {
    "rarity": "Advanced",
    "effectCurrent": "Crossbow Reload Speed +5\nComplete Reload 50 times to transform into Marksman's Crank",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Sturdy"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Crossbow Reload Speed +5\nComplete Reload 50 times to transform into Marksman's Crank",
      "Crossbow Reload Speed +10\nComplete Reload 50 times to transform into Marksman's Crank"
    ]
  },
  "ART-41": {
    "rarity": "Legendary",
    "effectCurrent": "Attack Speed +3%\nTrue Damage +1",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Solar Blade"
    ],
    "currentValues": [
      {
        "label": "Attack Speed",
        "values": [
          "+3%",
          "+6%",
          "+9%",
          "+12%",
          "+15%"
        ]
      },
      {
        "label": "True Damage",
        "values": [
          "+1",
          "+1",
          "+2",
          "+2",
          "+2"
        ]
      }
    ],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-42": {
    "rarity": "Advanced",
    "effectCurrent": "Solar Blade Damage +3%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Solar Blade"
    ],
    "currentValues": [],
    "effectsByLevel": [],
    "artifactEffectLabel": "Selected effects"
  },
  "ART-43": {
    "rarity": "Legendary",
    "effectCurrent": "Weapon Damage: +5 / +10 / +15\nSheath / Unsheath invincibility duration bonus: +40% / +70% / +120%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Sturdy"
    ],
    "currentValues": [],
    "effectsByLevel": []
  },
  "ART-44": {
    "rarity": "Advanced",
    "effectCurrent": "Active Artifact (Cooldown: 10 seconds)\nRetrieve all Solar Blade that have fallen to the ground, dealing Solar Blade damage to enemies in the path",
    "mechanicCurrent": "Damage bonuses apply to Solar Blade retrieval damage.",
    "artifactCategories": [
      "Solar Blade"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Active Artifact (Cooldown: 10 seconds)\nRetrieve all Solar Blade that have fallen to the ground, dealing Solar Blade damage to enemies in the path",
      "Active Artifact (Cooldown: 8 seconds)\nRetrieve all Solar Blade that have fallen to the ground, dealing Solar Blade damage to enemies in the path",
      "Active Artifact (Cooldown: 6 seconds)\nRetrieve all Solar Blade that have fallen to the ground, dealing Solar Blade damage to enemies in the path",
      "Active Artifact (Cooldown: 4 seconds)\nRetrieve all Solar Blade that have fallen to the ground, dealing Solar Blade damage to enemies in the path",
      "Active Artifact (Cooldown: 2.5 seconds)\nRetrieve all Solar Blade that have fallen to the ground, dealing Solar Blade damage to enemies in the path"
    ]
  },
  "ART-45": {
    "rarity": "Advanced",
    "effectCurrent": "Increases Weapon Attack damage dealt to targets afflicted by Burn by 5%",
    "mechanicCurrent": null,
    "artifactCategories": [
      "Ember"
    ],
    "currentValues": [],
    "effectsByLevel": [
      "Increases Weapon Attack damage dealt to targets afflicted by Burn by 5%",
      "Increases Weapon Attack damage dealt to targets afflicted by Burn by 10%",
      "Increases Weapon Attack damage dealt to targets afflicted by Burn by 15%"
    ]
  }
};
